Add files via upload
nestifff/JavaBSU_Lab45 pull request #1
Opened 2020-10-04 07:21 UTC by nestifff

2020-10-05 19:47 UTC, VeronikaYastr requested changes

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/main/Main.java
> +        String fileToReadName = args[0];
Если я запущу программу без аргументов, она упадет
![image](https://user-images.githubusercontent.com/36198336/95121921-6badc980-0758-11eb-8ecd-3d5da143d5d8.png)

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/main/Main.java
> +        String logFileName = "logfile.txt";
Имя logFile и pathToFiles можно вынести в статические переменные на уровень класса.

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/main/Main.java
> +                logFile.createNewFile();
Результат этой операции не проверяется. Можно сделать какое-то сообщение, если результат будет false, чтобы пользователь знал, что с файлом что-то не то

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +            Scanner scanner = new Scanner(path);
Лучше этот сканер поместить в try ()

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        String name = params[0];
Может выйти за пределы массива и вылетит ArrayIndexOutOfBounds. Лучше добавить проверку и выбросить исключение

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        if (params[2].equals("")) {
~params[2].isEmpty()

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        Calendar updateDate  = Calendar.getInstance();
Обычно используют LocalDate для даты.

Не проще так?
Calendar updateDate = Calendar.getInsanse();
if (!params[2].isEmpty())
updateDate = getCalendarObject(params[2], simpleDateFormat);

Зачем делать ее null, а перед этим еще инициализировать?

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +    private String filePath;
Можно сделать final.
Или добавить get-set методы, если его можно будет менять.

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordRequestsHandler.java
> +        RequestType type = RequestType.NONE;
Можно не присваивать ничего, он все равно потом переопределяется ниже.

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordRequestsHandler.java
> +        List<CompanyRecord> recordsToSend = new ArrayList<>();
Здесь тоже не присваивать можно, все равно потом пересоздается

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/RequestType.java
> +        RequestType type = RequestType.NONE;
Зачем создавать лишнюю переменную, если можно в случае, если if выполнился сразу вернуть результат, а в конце вернуть None, если не было найдено ничего?)

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/requestlogger/RequestLogger.java
> +        int typeNum = Integer.parseInt(typeNumStr);
Можно в try-catch, вдруг там не распарсится в инт

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecord.java
> +    public String getName() {
Обычно еще set-методы делают сразу, чтобы можно было модифицировать объекты)

2020-10-05 19:47 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecord.java
> +    private String createString(String dateFormat, String deliver) {
Почему deliver?)🤔 delimiter мб?

2020-10-05 20:34 UTC, nestifff commented on src/com/bsu/main/Main.java
> +        String fileToReadName = args[0];
А как лучше сделать? Задать что-нибудь по умолчанию? 
String fileToReadName = "data.csv"; например так, а потом в блоке try/catch считать с аргументов? (Пока что сделала так)

2020-10-05 20:36 UTC, VeronikaYastr commented on src/com/bsu/main/Main.java
> +        String fileToReadName = args[0];
Сделать по дефолту какое-то имя и потом if(args.length == 2) присвоить новые имена файлам

2020-10-05 20:41 UTC, nestifff commented on src/com/bsu/main/Main.java
> +        String logFileName = "logfile.txt";
Ок

2020-10-05 20:46 UTC, nestifff commented on src/com/bsu/main/Main.java
> +                logFile.createNewFile();
Ок. Не уверена, что нормально сделала:

if (!logFile.exists()) {
        if (!logFile.createNewFile()) {
                System.out.println("Something wrong with creating logfile");
        }
 }

2020-10-05 20:51 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +            Scanner scanner = new Scanner(path);
Ок

2020-10-05 20:55 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        String name = params[0];
Ок

2020-10-05 20:56 UTC, VeronikaYastr commented on src/com/bsu/main/Main.java
> +                logFile.createNewFile();
Нормально)

2020-10-05 20:57 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordRequestsHandler.java
> +        List<CompanyRecord> recordsToSend = new ArrayList<>();
Ок. 
Ну чисто объявила, чтобы в каждом case не пришлось тип снова писать

2020-10-05 20:58 UTC, nestifff commented on src/com/bsu/companyrecord/RequestType.java
> +        RequestType type = RequestType.NONE;
Точно!)

2020-10-05 21:00 UTC, nestifff commented on src/com/bsu/requestlogger/RequestLogger.java
> +        int typeNum = Integer.parseInt(typeNumStr);
ок

2020-10-05 21:02 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecord.java
> +    public String getName() {
Ок. 
Ну я только в этот класс, CompanyRecord, добавила

2020-10-05 21:02 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecord.java
> +    private String createString(String dateFormat, String deliver) {
Ага)

2020-10-05 21:10 UTC, nestifff commented on src/com/bsu/main/Main.java
> +        String fileToReadName = args[0];
Ок

2020-10-05 21:12 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        if (params[2].equals("")) {
Там не равно, да? А какая разница?

2020-10-05 21:15 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +    private String filePath;
Ок. Добавила get, set

2020-10-05 21:16 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordRequestsHandler.java
> +        RequestType type = RequestType.NONE;
Ок

2020-10-05 21:21 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        Calendar updateDate  = Calendar.getInstance();
Да, согласна)
Сделала

2020-10-05 21:23 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordRequestsHandler.java
> +        List<CompanyRecord> recordsToSend = new ArrayList<>();
Так все равно пишешь) По крайней мере подчеркивает идея, что эта инициализация никогда не сработает)

2020-10-05 21:25 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        if (params[2].equals("")) {
По смыслу никакой, но формально вызвать метод isEmpty более наглядно чем сравнивать с пустой строкой)

2020-10-05 21:34 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecordReader.java
> +        if (params[2].equals("")) {
Хорошо, исправила

2020-10-06 16:38 UTC, VeronikaYastr commented on src/com/bsu/companyrecord/CompanyRecord.java
> +
Забыла написать, что в классах обычно переопределяют методы hashCode и equals, надо бы их добавить)

2020-10-07 19:01 UTC, nestifff commented on src/com/bsu/companyrecord/CompanyRecord.java
> +
Сделала

2020-10-15 06:22 UTC, merged